name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [16]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.version }}

      - name: Install ddependencies
        run: |
          npm install
      - name: Run build
        run: |
          npm run build --if-present
